# Generated by Django 4.2.16 on 2024-09-16 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('deleted', models.BooleanField(default=False)),
                ('followed', models.ManyToManyField(related_name='followers', to='users.socialmediauser')),
            ],
            options={
                'abstract': False,
            },
            bases=('auth.user', models.Model),
        ),
    ]
