# Generated by Django 4.2.16 on 2024-09-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmediauser',
            options={'verbose_name': 'SocialMediaUser', 'verbose_name_plural': 'SocialMediaUsers'},
        ),
    ]
