# Generated by Django 4.2.16 on 2024-09-18 16:04

from django.db import migrations
from apps.users.services.init_user import init_user


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_user)
    ]
